#
# install apps
#
- name: install gems
  gem:
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: "{{ gem_packages }}"
  when: gem_packages
  become: False
